backend:
  name: github
  repo: OXIUMLABS /OXIUM # Nombre exacto de tu usuario/repositorio en GitHub
  branch: main # o master (según la rama principal de tu repositorio)
  base_url: https://decap-oauth-master.vercel.app
  auth_endpoint: /auth

# Dónde se guardarán y publicarán las fotos subidas
media_folder: "images"
public_folder: "images"

collections:
  - name: "products"
    label: "Productos del Catálogo"
    label_singular: "Producto"
    folder: "content/products" # Crea una carpeta de datos
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ID del Producto", name: "id", widget: "string" }
      - { label: "Nombre de la Prenda", name: "name", widget: "string" }
      - { label: "Precio (MXN)", name: "price", widget: "number", value_type: "int" }
      - { label: "Descripción Técnica", name: "desc", widget: "text" }
      - { label: "Imagen del Producto", name: "image", widget: "image" }
      - label: "Categoría"
        name: "category"
        widget: "select"
        options:
          - { label: "Top", value: "top" }
          - { label: "Bottoms", value: "bottoms" }
          - { label: "Accessories", value: "accessories" }
          - { label: "Jewelry", value: "jewelry" }
          - { label: "Backpacks", value: "backpacks" }
